// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'postnatal_visit.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$PostnatalVisitImpl _$$PostnatalVisitImplFromJson(Map<String, dynamic> json) =>
    _$PostnatalVisitImpl(
      id: json['id'] as String,
      maternalProfileId: json['maternalProfileId'] as String,
      childId: json['childId'] as String?,
      contactNumber: (json['contactNumber'] as num).toInt(),
      visitDate: DateTime.parse(json['visitDate'] as String),
      timingLabel: json['timingLabel'] as String?,
      bloodPressure: json['bloodPressure'] as String?,
      temperature: (json['temperature'] as num?)?.toDouble(),
      pulseRate: (json['pulseRate'] as num?)?.toInt(),
      respiratoryRate: (json['respiratoryRate'] as num?)?.toInt(),
      generalCondition: json['generalCondition'] as String?,
      breastCondition: json['breastCondition'] as String?,
      breastEngorgement: json['breastEngorgement'] as bool?,
      crackedNipples: json['crackedNipples'] as bool?,
      mastitis: json['mastitis'] as bool?,
      csScarCondition: json['csScarCondition'] as String?,
      uterusInvolution: json['uterusInvolution'] as String?,
      pelvicExam: json['pelvicExam'] as String?,
      episiotomyCondition: json['episiotomyCondition'] as String?,
      lochiaSmell: json['lochiaSmell'] as String?,
      lochiaAmount: json['lochiaAmount'] as String?,
      lochiaColor: json['lochiaColor'] as String?,
      haemoglobin: (json['haemoglobin'] as num?)?.toDouble(),
      motherHivTested: json['motherHivTested'] as bool?,
      motherHivResult: json['motherHivResult'] as String?,
      motherOnHaart: json['motherOnHaart'] as bool?,
      haartRegimen: json['haartRegimen'] as String?,
      fpCounselingDone: json['fpCounselingDone'] as bool?,
      fpMethodChosen: json['fpMethodChosen'] as String?,
      fpMethodProvided: json['fpMethodProvided'] as bool?,
      maternalMentalHealthScreened:
          json['maternalMentalHealthScreened'] as bool?,
      mentalHealthStatus: json['mentalHealthStatus'] as String?,
      babyGeneralCondition: json['babyGeneralCondition'] as String?,
      babyTemperature: (json['babyTemperature'] as num?)?.toDouble(),
      babyBreathsPerMinute: (json['babyBreathsPerMinute'] as num?)?.toInt(),
      exclusiveBreastfeeding: json['exclusiveBreastfeeding'] as bool?,
      breastfeedingPositioning: json['breastfeedingPositioning'] as String?,
      breastfeedingAttachment: json['breastfeedingAttachment'] as String?,
      umbilicalCordStatus: json['umbilicalCordStatus'] as String?,
      babyImmunizationStarted: json['babyImmunizationStarted'] as bool?,
      babyHivExposed: json['babyHivExposed'] as bool?,
      babyOnArvProphylaxis: json['babyOnArvProphylaxis'] as bool?,
      babyOnCtxProphylaxis: json['babyOnCtxProphylaxis'] as bool?,
      babyIrritable: json['babyIrritable'] as bool?,
      otherBabyProblems: json['otherBabyProblems'] as String?,
      motherNotes: json['motherNotes'] as String?,
      babyNotes: json['babyNotes'] as String?,
      diagnosis: json['diagnosis'] as String?,
      treatment: json['treatment'] as String?,
      nextVisitDate: json['nextVisitDate'] == null
          ? null
          : DateTime.parse(json['nextVisitDate'] as String),
      healthWorkerName: json['healthWorkerName'] as String?,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$$PostnatalVisitImplToJson(
        _$PostnatalVisitImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'maternalProfileId': instance.maternalProfileId,
      'childId': instance.childId,
      'contactNumber': instance.contactNumber,
      'visitDate': instance.visitDate.toIso8601String(),
      'timingLabel': instance.timingLabel,
      'bloodPressure': instance.bloodPressure,
      'temperature': instance.temperature,
      'pulseRate': instance.pulseRate,
      'respiratoryRate': instance.respiratoryRate,
      'generalCondition': instance.generalCondition,
      'breastCondition': instance.breastCondition,
      'breastEngorgement': instance.breastEngorgement,
      'crackedNipples': instance.crackedNipples,
      'mastitis': instance.mastitis,
      'csScarCondition': instance.csScarCondition,
      'uterusInvolution': instance.uterusInvolution,
      'pelvicExam': instance.pelvicExam,
      'episiotomyCondition': instance.episiotomyCondition,
      'lochiaSmell': instance.lochiaSmell,
      'lochiaAmount': instance.lochiaAmount,
      'lochiaColor': instance.lochiaColor,
      'haemoglobin': instance.haemoglobin,
      'motherHivTested': instance.motherHivTested,
      'motherHivResult': instance.motherHivResult,
      'motherOnHaart': instance.motherOnHaart,
      'haartRegimen': instance.haartRegimen,
      'fpCounselingDone': instance.fpCounselingDone,
      'fpMethodChosen': instance.fpMethodChosen,
      'fpMethodProvided': instance.fpMethodProvided,
      'maternalMentalHealthScreened': instance.maternalMentalHealthScreened,
      'mentalHealthStatus': instance.mentalHealthStatus,
      'babyGeneralCondition': instance.babyGeneralCondition,
      'babyTemperature': instance.babyTemperature,
      'babyBreathsPerMinute': instance.babyBreathsPerMinute,
      'exclusiveBreastfeeding': instance.exclusiveBreastfeeding,
      'breastfeedingPositioning': instance.breastfeedingPositioning,
      'breastfeedingAttachment': instance.breastfeedingAttachment,
      'umbilicalCordStatus': instance.umbilicalCordStatus,
      'babyImmunizationStarted': instance.babyImmunizationStarted,
      'babyHivExposed': instance.babyHivExposed,
      'babyOnArvProphylaxis': instance.babyOnArvProphylaxis,
      'babyOnCtxProphylaxis': instance.babyOnCtxProphylaxis,
      'babyIrritable': instance.babyIrritable,
      'otherBabyProblems': instance.otherBabyProblems,
      'motherNotes': instance.motherNotes,
      'babyNotes': instance.babyNotes,
      'diagnosis': instance.diagnosis,
      'treatment': instance.treatment,
      'nextVisitDate': instance.nextVisitDate?.toIso8601String(),
      'healthWorkerName': instance.healthWorkerName,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
    };
