// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'child_profile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ChildProfileImpl _$$ChildProfileImplFromJson(Map<String, dynamic> json) =>
    _$ChildProfileImpl(
      id: json['id'] as String,
      maternalProfileId: json['maternal_profile_id'] as String,
      childName: json['child_name'] as String,
      sex: json['sex'] as String,
      dateOfBirth: DateTime.parse(json['date_of_birth'] as String),
      dateFirstSeen: DateTime.parse(json['date_first_seen'] as String),
      gestationAtBirthWeeks: (json['gestation_at_birth_weeks'] as num).toInt(),
      birthWeightGrams: (json['birth_weight_grams'] as num).toDouble(),
      birthLengthCm: (json['birth_length_cm'] as num).toDouble(),
      headCircumferenceCm:
          (json['head_circumference_at_birth_cm'] as num?)?.toDouble(),
      otherBirthCharacteristics: json['other_birth_characteristics'] as String?,
      birthOrder: (json['birth_order'] as num?)?.toInt(),
      placeOfBirth: json['place_of_birth'] as String,
      healthFacilityName: json['health_facility_name'] as String?,
      birthNotificationNumber: json['birth_notification_number'] as String?,
      birthNotificationDate: json['birth_notification_date'] == null
          ? null
          : DateTime.parse(json['birth_notification_date'] as String),
      immunizationRegNumber: json['immunization_reg_number'] as String?,
      cwcNumber: json['cwc_number'] as String?,
      kmhflCode: json['kmhfl_code'] as String?,
      birthCertificateNumber: json['birth_certificate_number'] as String?,
      birthRegistrationDate: json['birth_registration_date'] == null
          ? null
          : DateTime.parse(json['birth_registration_date'] as String),
      birthRegistrationPlace: json['birth_registration_place'] as String?,
      fatherName: json['father_name'] as String?,
      fatherPhone: json['father_phone'] as String?,
      motherName: json['mother_name'] as String?,
      motherPhone: json['mother_phone'] as String?,
      guardianName: json['guardian_name'] as String?,
      guardianPhone: json['guardian_phone'] as String?,
      county: json['county'] as String?,
      subCounty: json['sub_county'] as String?,
      ward: json['ward'] as String?,
      village: json['village'] as String?,
      physicalAddress: json['physical_address'] as String?,
      weightAtFirstContact:
          (json['weight_at_first_contact'] as num?)?.toDouble(),
      lengthAtFirstContact:
          (json['length_at_first_contact'] as num?)?.toDouble(),
      zScore: json['z_score'] as String?,
      hivExposed: json['hiv_exposed'] as bool?,
      hivStatus: json['hiv_status'] as String?,
      hivTestDate: json['hiv_test_date'] == null
          ? null
          : DateTime.parse(json['hiv_test_date'] as String),
      haemoglobin: (json['haemoglobin'] as num?)?.toDouble(),
      colouration: json['colouration'] as String?,
      eyes: json['eyes'] as String?,
      ears: json['ears'] as String?,
      mouth: json['mouth'] as String?,
      chest: json['chest'] as String?,
      heart: json['heart'] as String?,
      abdomen: json['abdomen'] as String?,
      umbilicalCord: json['umbilical_cord'] as String?,
      spine: json['spine'] as String?,
      armsHands: json['arms_hands'] as String?,
      legsFeet: json['legs_feet'] as String?,
      genitalia: json['genitalia'] as String?,
      anus: json['anus'] as String?,
      tbScreened: json['tb_screened'] as bool?,
      tbScreeningResult: json['tb_screening_result'] as String?,
      breastfeedingWell: json['breastfeeding_well'] as bool?,
      breastfeedingPoorly: json['breastfeeding_poorly'] as bool?,
      unableToBreastfeed: json['unable_to_breastfeed'] as bool?,
      otherFoodsIntroducedBelow6Months:
          json['other_foods_introduced_below_6_months'] as bool?,
      ageOtherFoodsIntroduced:
          (json['age_other_foods_introduced'] as num?)?.toInt(),
      complementaryFoodFrom6Months:
          json['complementary_food_from_6_months'] as bool?,
      sleepProblems: json['sleep_problems'] as String?,
      irritability: json['irritability'] as bool?,
      otherProblems: json['other_problems'] as String?,
      birthWeightLessThan2500g: json['birth_weight_less_than_2500g'] as bool?,
      birthLessThan2YearsAfterLast:
          json['birth_less_than_2_years_after_last'] as bool?,
      fifthChildOrMore: json['fifth_child_or_more'] as bool?,
      bornOfTeenageMother: json['born_of_teenage_mother'] as bool?,
      bornOfMentallyIllMother: json['born_of_mentally_ill_mother'] as bool?,
      developmentalDelays: json['developmental_delays'] as bool?,
      siblingUndernourished: json['sibling_undernourished'] as bool?,
      multipleBirth: json['multiple_birth'] as bool?,
      childWithSpecialNeeds: json['child_with_special_needs'] as bool?,
      orphanVulnerableChild: json['orphan_vulnerable_child'] as bool?,
      childWithDisability: json['child_with_disability'] as bool?,
      historyOfChildAbuse: json['history_of_child_abuse'] as bool?,
      cleftLipPalate: json['cleft_lip_palate'] as bool?,
      otherSpecialCareReason: json['other_special_care_reason'] as String?,
      createdAt: json['created_at'] == null
          ? null
          : DateTime.parse(json['created_at'] as String),
      updatedAt: json['updated_at'] == null
          ? null
          : DateTime.parse(json['updated_at'] as String),
    );

Map<String, dynamic> _$$ChildProfileImplToJson(_$ChildProfileImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'maternal_profile_id': instance.maternalProfileId,
      'child_name': instance.childName,
      'sex': instance.sex,
      'date_of_birth': instance.dateOfBirth.toIso8601String(),
      'date_first_seen': instance.dateFirstSeen.toIso8601String(),
      'gestation_at_birth_weeks': instance.gestationAtBirthWeeks,
      'birth_weight_grams': instance.birthWeightGrams,
      'birth_length_cm': instance.birthLengthCm,
      'head_circumference_at_birth_cm': instance.headCircumferenceCm,
      'other_birth_characteristics': instance.otherBirthCharacteristics,
      'birth_order': instance.birthOrder,
      'place_of_birth': instance.placeOfBirth,
      'health_facility_name': instance.healthFacilityName,
      'birth_notification_number': instance.birthNotificationNumber,
      'birth_notification_date':
          instance.birthNotificationDate?.toIso8601String(),
      'immunization_reg_number': instance.immunizationRegNumber,
      'cwc_number': instance.cwcNumber,
      'kmhfl_code': instance.kmhflCode,
      'birth_certificate_number': instance.birthCertificateNumber,
      'birth_registration_date':
          instance.birthRegistrationDate?.toIso8601String(),
      'birth_registration_place': instance.birthRegistrationPlace,
      'father_name': instance.fatherName,
      'father_phone': instance.fatherPhone,
      'mother_name': instance.motherName,
      'mother_phone': instance.motherPhone,
      'guardian_name': instance.guardianName,
      'guardian_phone': instance.guardianPhone,
      'county': instance.county,
      'sub_county': instance.subCounty,
      'ward': instance.ward,
      'village': instance.village,
      'physical_address': instance.physicalAddress,
      'weight_at_first_contact': instance.weightAtFirstContact,
      'length_at_first_contact': instance.lengthAtFirstContact,
      'z_score': instance.zScore,
      'hiv_exposed': instance.hivExposed,
      'hiv_status': instance.hivStatus,
      'hiv_test_date': instance.hivTestDate?.toIso8601String(),
      'haemoglobin': instance.haemoglobin,
      'colouration': instance.colouration,
      'eyes': instance.eyes,
      'ears': instance.ears,
      'mouth': instance.mouth,
      'chest': instance.chest,
      'heart': instance.heart,
      'abdomen': instance.abdomen,
      'umbilical_cord': instance.umbilicalCord,
      'spine': instance.spine,
      'arms_hands': instance.armsHands,
      'legs_feet': instance.legsFeet,
      'genitalia': instance.genitalia,
      'anus': instance.anus,
      'tb_screened': instance.tbScreened,
      'tb_screening_result': instance.tbScreeningResult,
      'breastfeeding_well': instance.breastfeedingWell,
      'breastfeeding_poorly': instance.breastfeedingPoorly,
      'unable_to_breastfeed': instance.unableToBreastfeed,
      'other_foods_introduced_below_6_months':
          instance.otherFoodsIntroducedBelow6Months,
      'age_other_foods_introduced': instance.ageOtherFoodsIntroduced,
      'complementary_food_from_6_months': instance.complementaryFoodFrom6Months,
      'sleep_problems': instance.sleepProblems,
      'irritability': instance.irritability,
      'other_problems': instance.otherProblems,
      'birth_weight_less_than_2500g': instance.birthWeightLessThan2500g,
      'birth_less_than_2_years_after_last':
          instance.birthLessThan2YearsAfterLast,
      'fifth_child_or_more': instance.fifthChildOrMore,
      'born_of_teenage_mother': instance.bornOfTeenageMother,
      'born_of_mentally_ill_mother': instance.bornOfMentallyIllMother,
      'developmental_delays': instance.developmentalDelays,
      'sibling_undernourished': instance.siblingUndernourished,
      'multiple_birth': instance.multipleBirth,
      'child_with_special_needs': instance.childWithSpecialNeeds,
      'orphan_vulnerable_child': instance.orphanVulnerableChild,
      'child_with_disability': instance.childWithDisability,
      'history_of_child_abuse': instance.historyOfChildAbuse,
      'cleft_lip_palate': instance.cleftLipPalate,
      'other_special_care_reason': instance.otherSpecialCareReason,
      'created_at': instance.createdAt?.toIso8601String(),
      'updated_at': instance.updatedAt?.toIso8601String(),
    };
