// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'child_profile.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ChildProfileImpl _$$ChildProfileImplFromJson(Map<String, dynamic> json) =>
    _$ChildProfileImpl(
      id: json['id'] as String,
      maternalProfileId: json['maternalProfileId'] as String,
      childName: json['childName'] as String,
      sex: json['sex'] as String,
      dateOfBirth: DateTime.parse(json['dateOfBirth'] as String),
      dateFirstSeen: DateTime.parse(json['dateFirstSeen'] as String),
      gestationAtBirthWeeks: (json['gestationAtBirthWeeks'] as num).toInt(),
      birthWeightGrams: (json['birthWeightGrams'] as num).toDouble(),
      birthLengthCm: (json['birthLengthCm'] as num).toDouble(),
      headCircumferenceCm: (json['headCircumferenceCm'] as num?)?.toDouble(),
      otherBirthCharacteristics: json['otherBirthCharacteristics'] as String?,
      birthOrder: (json['birthOrder'] as num?)?.toInt(),
      placeOfBirth: json['placeOfBirth'] as String,
      healthFacilityName: json['healthFacilityName'] as String?,
      birthNotificationNumber: json['birthNotificationNumber'] as String?,
      birthNotificationDate: json['birthNotificationDate'] == null
          ? null
          : DateTime.parse(json['birthNotificationDate'] as String),
      immunizationRegNumber: json['immunizationRegNumber'] as String?,
      cwcNumber: json['cwcNumber'] as String?,
      kmhflCode: json['kmhflCode'] as String?,
      birthCertificateNumber: json['birthCertificateNumber'] as String?,
      birthRegistrationDate: json['birthRegistrationDate'] == null
          ? null
          : DateTime.parse(json['birthRegistrationDate'] as String),
      birthRegistrationPlace: json['birthRegistrationPlace'] as String?,
      fatherName: json['fatherName'] as String?,
      fatherPhone: json['fatherPhone'] as String?,
      motherName: json['motherName'] as String?,
      motherPhone: json['motherPhone'] as String?,
      guardianName: json['guardianName'] as String?,
      guardianPhone: json['guardianPhone'] as String?,
      county: json['county'] as String?,
      subCounty: json['subCounty'] as String?,
      ward: json['ward'] as String?,
      village: json['village'] as String?,
      physicalAddress: json['physicalAddress'] as String?,
      weightAtFirstContact: (json['weightAtFirstContact'] as num?)?.toDouble(),
      lengthAtFirstContact: (json['lengthAtFirstContact'] as num?)?.toDouble(),
      zScore: json['zScore'] as String?,
      hivExposed: json['hivExposed'] as bool?,
      hivStatus: json['hivStatus'] as String?,
      hivTestDate: json['hivTestDate'] == null
          ? null
          : DateTime.parse(json['hivTestDate'] as String),
      haemoglobin: (json['haemoglobin'] as num?)?.toDouble(),
      colouration: json['colouration'] as String?,
      eyes: json['eyes'] as String?,
      ears: json['ears'] as String?,
      mouth: json['mouth'] as String?,
      chest: json['chest'] as String?,
      heart: json['heart'] as String?,
      abdomen: json['abdomen'] as String?,
      umbilicalCord: json['umbilicalCord'] as String?,
      spine: json['spine'] as String?,
      armsHands: json['armsHands'] as String?,
      legsFeet: json['legsFeet'] as String?,
      genitalia: json['genitalia'] as String?,
      anus: json['anus'] as String?,
      tbScreened: json['tbScreened'] as bool?,
      tbScreeningResult: json['tbScreeningResult'] as String?,
      breastfeedingWell: json['breastfeedingWell'] as bool?,
      breastfeedingPoorly: json['breastfeedingPoorly'] as bool?,
      unableToBreastfeed: json['unableToBreastfeed'] as bool?,
      otherFoodsIntroducedBelow6Months:
          json['otherFoodsIntroducedBelow6Months'] as bool?,
      ageOtherFoodsIntroduced:
          (json['ageOtherFoodsIntroduced'] as num?)?.toInt(),
      complementaryFoodFrom6Months:
          json['complementaryFoodFrom6Months'] as bool?,
      sleepProblems: json['sleepProblems'] as String?,
      irritability: json['irritability'] as bool?,
      otherProblems: json['otherProblems'] as String?,
      birthWeightLessThan2500g: json['birthWeightLessThan2500g'] as bool?,
      birthLessThan2YearsAfterLast:
          json['birthLessThan2YearsAfterLast'] as bool?,
      fifthChildOrMore: json['fifthChildOrMore'] as bool?,
      bornOfTeenageMother: json['bornOfTeenageMother'] as bool?,
      bornOfMentallyIllMother: json['bornOfMentallyIllMother'] as bool?,
      developmentalDelays: json['developmentalDelays'] as bool?,
      siblingUndernourished: json['siblingUndernourished'] as bool?,
      multipleBirth: json['multipleBirth'] as bool?,
      childWithSpecialNeeds: json['childWithSpecialNeeds'] as bool?,
      orphanVulnerableChild: json['orphanVulnerableChild'] as bool?,
      childWithDisability: json['childWithDisability'] as bool?,
      historyOfChildAbuse: json['historyOfChildAbuse'] as bool?,
      cleftLipPalate: json['cleftLipPalate'] as bool?,
      otherSpecialCareReason: json['otherSpecialCareReason'] as String?,
      createdAt: json['createdAt'] == null
          ? null
          : DateTime.parse(json['createdAt'] as String),
      updatedAt: json['updatedAt'] == null
          ? null
          : DateTime.parse(json['updatedAt'] as String),
    );

Map<String, dynamic> _$$ChildProfileImplToJson(_$ChildProfileImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'maternalProfileId': instance.maternalProfileId,
      'childName': instance.childName,
      'sex': instance.sex,
      'dateOfBirth': instance.dateOfBirth.toIso8601String(),
      'dateFirstSeen': instance.dateFirstSeen.toIso8601String(),
      'gestationAtBirthWeeks': instance.gestationAtBirthWeeks,
      'birthWeightGrams': instance.birthWeightGrams,
      'birthLengthCm': instance.birthLengthCm,
      'headCircumferenceCm': instance.headCircumferenceCm,
      'otherBirthCharacteristics': instance.otherBirthCharacteristics,
      'birthOrder': instance.birthOrder,
      'placeOfBirth': instance.placeOfBirth,
      'healthFacilityName': instance.healthFacilityName,
      'birthNotificationNumber': instance.birthNotificationNumber,
      'birthNotificationDate':
          instance.birthNotificationDate?.toIso8601String(),
      'immunizationRegNumber': instance.immunizationRegNumber,
      'cwcNumber': instance.cwcNumber,
      'kmhflCode': instance.kmhflCode,
      'birthCertificateNumber': instance.birthCertificateNumber,
      'birthRegistrationDate':
          instance.birthRegistrationDate?.toIso8601String(),
      'birthRegistrationPlace': instance.birthRegistrationPlace,
      'fatherName': instance.fatherName,
      'fatherPhone': instance.fatherPhone,
      'motherName': instance.motherName,
      'motherPhone': instance.motherPhone,
      'guardianName': instance.guardianName,
      'guardianPhone': instance.guardianPhone,
      'county': instance.county,
      'subCounty': instance.subCounty,
      'ward': instance.ward,
      'village': instance.village,
      'physicalAddress': instance.physicalAddress,
      'weightAtFirstContact': instance.weightAtFirstContact,
      'lengthAtFirstContact': instance.lengthAtFirstContact,
      'zScore': instance.zScore,
      'hivExposed': instance.hivExposed,
      'hivStatus': instance.hivStatus,
      'hivTestDate': instance.hivTestDate?.toIso8601String(),
      'haemoglobin': instance.haemoglobin,
      'colouration': instance.colouration,
      'eyes': instance.eyes,
      'ears': instance.ears,
      'mouth': instance.mouth,
      'chest': instance.chest,
      'heart': instance.heart,
      'abdomen': instance.abdomen,
      'umbilicalCord': instance.umbilicalCord,
      'spine': instance.spine,
      'armsHands': instance.armsHands,
      'legsFeet': instance.legsFeet,
      'genitalia': instance.genitalia,
      'anus': instance.anus,
      'tbScreened': instance.tbScreened,
      'tbScreeningResult': instance.tbScreeningResult,
      'breastfeedingWell': instance.breastfeedingWell,
      'breastfeedingPoorly': instance.breastfeedingPoorly,
      'unableToBreastfeed': instance.unableToBreastfeed,
      'otherFoodsIntroducedBelow6Months':
          instance.otherFoodsIntroducedBelow6Months,
      'ageOtherFoodsIntroduced': instance.ageOtherFoodsIntroduced,
      'complementaryFoodFrom6Months': instance.complementaryFoodFrom6Months,
      'sleepProblems': instance.sleepProblems,
      'irritability': instance.irritability,
      'otherProblems': instance.otherProblems,
      'birthWeightLessThan2500g': instance.birthWeightLessThan2500g,
      'birthLessThan2YearsAfterLast': instance.birthLessThan2YearsAfterLast,
      'fifthChildOrMore': instance.fifthChildOrMore,
      'bornOfTeenageMother': instance.bornOfTeenageMother,
      'bornOfMentallyIllMother': instance.bornOfMentallyIllMother,
      'developmentalDelays': instance.developmentalDelays,
      'siblingUndernourished': instance.siblingUndernourished,
      'multipleBirth': instance.multipleBirth,
      'childWithSpecialNeeds': instance.childWithSpecialNeeds,
      'orphanVulnerableChild': instance.orphanVulnerableChild,
      'childWithDisability': instance.childWithDisability,
      'historyOfChildAbuse': instance.historyOfChildAbuse,
      'cleftLipPalate': instance.cleftLipPalate,
      'otherSpecialCareReason': instance.otherSpecialCareReason,
      'createdAt': instance.createdAt?.toIso8601String(),
      'updatedAt': instance.updatedAt?.toIso8601String(),
    };
